2024-04-26 20:07:15,431 - aiogram.dispatcher - INFO - Start polling
2024-04-26 20:07:15,537 - aiogram.dispatcher - INFO - Run polling for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:07:32,539 - bot.handlers.user_handlers - INFO - User id=1071020716 is_bot=False first_name='Sergei' last_name='Zelenin' username='szely' language_code='ru' is_premium=None added_to_attachment_menu=None can_join_groups=None can_read_all_group_messages=None supports_inline_queries=None started the conversation.
2024-04-26 20:07:32,540 - aiogram.event - INFO - Update id=537262881 is handled. Duration 421 ms by bot id=7152099013
2024-04-26 20:07:33,969 - aiogram.event - INFO - Update id=537262882 is handled. Duration 493 ms by bot id=7152099013
2024-04-26 20:07:35,132 - aiogram.event - INFO - Update id=537262883 is handled. Duration 242 ms by bot id=7152099013
2024-04-26 20:07:36,814 - aiogram.event - INFO - Update id=537262884 is handled. Duration 103 ms by bot id=7152099013
2024-04-26 20:07:39,023 - aiogram.event - INFO - Update id=537262885 is handled. Duration 420 ms by bot id=7152099013
2024-04-26 20:07:41,519 - aiogram.event - INFO - Update id=537262886 is handled. Duration 154 ms by bot id=7152099013
2024-04-26 20:07:44,061 - aiogram.event - INFO - Update id=537262887 is handled. Duration 1601 ms by bot id=7152099013
2024-04-26 20:08:00,841 - aiogram.event - INFO - Update id=537262888 is handled. Duration 219 ms by bot id=7152099013
2024-04-26 20:08:02,716 - aiogram.event - INFO - Update id=537262889 is handled. Duration 192 ms by bot id=7152099013
2024-04-26 20:08:04,691 - aiogram.event - INFO - Update id=537262890 is handled. Duration 177 ms by bot id=7152099013
2024-04-26 20:08:06,966 - aiogram.event - INFO - Update id=537262891 is handled. Duration 1325 ms by bot id=7152099013
2024-04-26 20:08:08,110 - aiogram.event - INFO - Update id=537262892 is handled. Duration 103 ms by bot id=7152099013
2024-04-26 20:08:09,605 - aiogram.event - INFO - Update id=537262893 is handled. Duration 215 ms by bot id=7152099013
2024-04-26 20:11:23,429 - aiogram.dispatcher - WARNING - Received SIGINT signal
2024-04-26 20:11:23,436 - aiogram.dispatcher - INFO - Polling stopped for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:11:23,438 - aiogram.dispatcher - INFO - Polling stopped
2024-04-26 20:11:35,496 - aiogram.dispatcher - INFO - Start polling
2024-04-26 20:11:35,562 - aiogram.dispatcher - INFO - Run polling for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:11:38,936 - bot.handlers.user_handlers - INFO - User id=1071020716 is_bot=False first_name='Sergei' last_name='Zelenin' username='szely' language_code='ru' is_premium=None added_to_attachment_menu=None can_join_groups=None can_read_all_group_messages=None supports_inline_queries=None started the conversation.
2024-04-26 20:11:38,937 - aiogram.event - INFO - Update id=537262895 is handled. Duration 312 ms by bot id=7152099013
2024-04-26 20:11:41,110 - aiogram.event - INFO - Update id=537262896 is handled. Duration 1045 ms by bot id=7152099013
2024-04-26 20:11:44,354 - aiogram.event - INFO - Update id=537262897 is handled. Duration 341 ms by bot id=7152099013
2024-04-26 20:11:47,225 - aiogram.event - INFO - Update id=537262898 is handled. Duration 218 ms by bot id=7152099013
2024-04-26 20:11:49,307 - aiogram.event - INFO - Update id=537262899 is handled. Duration 1035 ms by bot id=7152099013
2024-04-26 20:11:53,196 - aiogram.event - INFO - Update id=537262900 is handled. Duration 1112 ms by bot id=7152099013
2024-04-26 20:11:55,325 - aiogram.event - INFO - Update id=537262901 is handled. Duration 862 ms by bot id=7152099013
2024-04-26 20:11:56,461 - aiogram.event - INFO - Update id=537262902 is handled. Duration 201 ms by bot id=7152099013
2024-04-26 20:11:59,151 - aiogram.event - INFO - Update id=537262903 is handled. Duration 148 ms by bot id=7152099013
2024-04-26 20:12:00,681 - aiogram.event - INFO - Update id=537262904 is handled. Duration 234 ms by bot id=7152099013
2024-04-26 20:12:02,937 - aiogram.event - INFO - Update id=537262905 is handled. Duration 239 ms by bot id=7152099013
2024-04-26 20:12:07,262 - aiogram.event - INFO - Update id=537262906 is handled. Duration 1159 ms by bot id=7152099013
2024-04-26 20:12:12,102 - aiogram.event - INFO - Update id=537262907 is handled. Duration 182 ms by bot id=7152099013
2024-04-26 20:12:18,552 - bot.handlers.user_handlers - INFO - User [User(id=1071020716, is_bot=False, first_name='Sergei', last_name='Zelenin', username='szely', language_code='ru', is_premium=None, added_to_attachment_menu=None, can_join_groups=None, can_read_all_group_messages=None, supports_inline_queries=None), 'прогноз'] search file.
2024-04-26 20:12:19,597 - aiogram.event - INFO - Update id=537262908 is handled. Duration 1098 ms by bot id=7152099013
2024-04-26 20:12:21,849 - aiogram.event - INFO - Update id=537262909 is handled. Duration 152 ms by bot id=7152099013
2024-04-26 20:12:26,672 - aiogram.event - INFO - Update id=537262910 is handled. Duration 1740 ms by bot id=7152099013
2024-04-26 20:12:32,617 - aiogram.event - INFO - Update id=537262911 is handled. Duration 130 ms by bot id=7152099013
2024-04-26 20:12:39,464 - aiogram.event - INFO - Update id=537262912 is handled. Duration 3848 ms by bot id=7152099013
2024-04-26 20:22:58,561 - aiogram.dispatcher - WARNING - Received SIGINT signal
2024-04-26 20:22:58,614 - aiogram.dispatcher - INFO - Polling stopped for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:22:58,618 - aiogram.dispatcher - INFO - Polling stopped
2024-04-26 20:23:07,044 - aiogram.dispatcher - INFO - Start polling
2024-04-26 20:23:07,116 - aiogram.dispatcher - INFO - Run polling for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:23:14,995 - bot.handlers.user_handlers - INFO - User id=1071020716 is_bot=False first_name='Sergei' last_name='Zelenin' username='szely' language_code='ru' is_premium=None added_to_attachment_menu=None can_join_groups=None can_read_all_group_messages=None supports_inline_queries=None started the conversation.
2024-04-26 20:23:14,996 - aiogram.event - INFO - Update id=537262913 is handled. Duration 340 ms by bot id=7152099013
2024-04-26 20:23:17,740 - aiogram.event - INFO - Update id=537262914 is handled. Duration 476 ms by bot id=7152099013
2024-04-26 20:23:18,822 - aiogram.event - INFO - Update id=537262915 is handled. Duration 299 ms by bot id=7152099013
2024-04-26 20:23:21,406 - aiogram.event - INFO - Update id=537262916 is handled. Duration 135 ms by bot id=7152099013
2024-04-26 20:23:25,435 - bot.handlers.user_handlers - INFO - User [User(id=1071020716, is_bot=False, first_name='Sergei', last_name='Zelenin', username='szely', language_code='ru', is_premium=None, added_to_attachment_menu=None, can_join_groups=None, can_read_all_group_messages=None, supports_inline_queries=None), 'бюд'] search file.
2024-04-26 20:23:28,480 - aiogram.event - INFO - Update id=537262917 is handled. Duration 3055 ms by bot id=7152099013
2024-04-26 20:23:33,888 - aiogram.event - INFO - Update id=537262918 is handled. Duration 131 ms by bot id=7152099013
2024-04-26 20:23:38,971 - aiogram.event - INFO - Update id=537262919 is not handled. Duration 1543 ms by bot id=7152099013
2024-04-26 20:23:38,971 - aiogram.event - ERROR - Cause exception while process update id=537262919 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:23:49,369 - aiogram.event - INFO - Update id=537262920 is handled. Duration 159 ms by bot id=7152099013
2024-04-26 20:23:54,161 - aiogram.event - INFO - Update id=537262921 is not handled. Duration 1418 ms by bot id=7152099013
2024-04-26 20:23:54,161 - aiogram.event - ERROR - Cause exception while process update id=537262921 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:24:01,563 - aiogram.event - INFO - Update id=537262922 is not handled. Duration 1276 ms by bot id=7152099013
2024-04-26 20:24:01,564 - aiogram.event - ERROR - Cause exception while process update id=537262922 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:24:06,190 - aiogram.event - INFO - Update id=537262923 is handled. Duration 190 ms by bot id=7152099013
2024-04-26 20:24:11,338 - aiogram.event - INFO - Update id=537262924 is not handled. Duration 1583 ms by bot id=7152099013
2024-04-26 20:24:11,346 - aiogram.event - ERROR - Cause exception while process update id=537262924 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:25:30,595 - aiogram.dispatcher - WARNING - Received SIGINT signal
2024-04-26 20:25:30,605 - aiogram.dispatcher - INFO - Polling stopped for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:25:30,605 - aiogram.dispatcher - INFO - Polling stopped
2024-04-26 20:25:42,520 - aiogram.dispatcher - INFO - Start polling
2024-04-26 20:25:42,581 - aiogram.dispatcher - INFO - Run polling for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:25:45,614 - bot.handlers.user_handlers - INFO - User id=1071020716 is_bot=False first_name='Sergei' last_name='Zelenin' username='szely' language_code='ru' is_premium=None added_to_attachment_menu=None can_join_groups=None can_read_all_group_messages=None supports_inline_queries=None started the conversation.
2024-04-26 20:25:45,617 - aiogram.event - INFO - Update id=537262925 is handled. Duration 307 ms by bot id=7152099013
2024-04-26 20:25:47,535 - aiogram.event - INFO - Update id=537262926 is handled. Duration 794 ms by bot id=7152099013
2024-04-26 20:25:48,841 - aiogram.event - INFO - Update id=537262927 is handled. Duration 397 ms by bot id=7152099013
2024-04-26 20:25:50,315 - aiogram.event - INFO - Update id=537262928 is handled. Duration 156 ms by bot id=7152099013
2024-04-26 20:25:55,261 - bot.handlers.user_handlers - INFO - User [User(id=1071020716, is_bot=False, first_name='Sergei', last_name='Zelenin', username='szely', language_code='ru', is_premium=None, added_to_attachment_menu=None, can_join_groups=None, can_read_all_group_messages=None, supports_inline_queries=None), 'бюд'] search file.
2024-04-26 20:25:58,692 - aiogram.event - INFO - Update id=537262929 is handled. Duration 3435 ms by bot id=7152099013
2024-04-26 20:26:01,759 - aiogram.event - INFO - Update id=537262930 is handled. Duration 114 ms by bot id=7152099013
2024-04-26 20:26:06,055 - aiogram.event - INFO - Update id=537262931 is not handled. Duration 1195 ms by bot id=7152099013
2024-04-26 20:26:06,056 - aiogram.event - ERROR - Cause exception while process update id=537262931 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav).replace(' ','')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:26:13,233 - aiogram.event - INFO - Update id=537262932 is handled. Duration 162 ms by bot id=7152099013
2024-04-26 20:26:20,945 - aiogram.event - INFO - Update id=537262933 is handled. Duration 4701 ms by bot id=7152099013
2024-04-26 20:26:51,370 - aiogram.dispatcher - WARNING - Received SIGINT signal
2024-04-26 20:26:51,371 - aiogram.dispatcher - INFO - Polling stopped for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:26:51,372 - aiogram.dispatcher - INFO - Polling stopped
2024-04-26 20:27:00,113 - aiogram.dispatcher - INFO - Start polling
2024-04-26 20:27:00,173 - aiogram.dispatcher - INFO - Run polling for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:27:01,878 - aiogram.event - INFO - Update id=537262934 is handled. Duration 264 ms by bot id=7152099013
2024-04-26 20:27:08,380 - aiogram.event - INFO - Update id=537262935 is not handled. Duration 1486 ms by bot id=7152099013
2024-04-26 20:27:08,380 - aiogram.event - ERROR - Cause exception while process update id=537262935 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:27:33,035 - aiogram.event - INFO - Update id=537262936 is handled. Duration 2192 ms by bot id=7152099013
2024-04-26 20:27:44,662 - aiogram.event - INFO - Update id=537262937 is handled. Duration 180 ms by bot id=7152099013
2024-04-26 20:27:49,693 - aiogram.event - INFO - Update id=537262938 is handled. Duration 1672 ms by bot id=7152099013
2024-04-26 20:27:59,705 - aiogram.event - INFO - Update id=537262939 is handled. Duration 126 ms by bot id=7152099013
2024-04-26 20:28:04,398 - aiogram.event - INFO - Update id=537262940 is not handled. Duration 1618 ms by bot id=7152099013
2024-04-26 20:28:04,399 - aiogram.event - ERROR - Cause exception while process update id=537262940 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:28:13,715 - aiogram.event - INFO - Update id=537262941 is handled. Duration 1951 ms by bot id=7152099013
2024-04-26 20:28:27,145 - aiogram.event - INFO - Update id=537262942 is handled. Duration 208 ms by bot id=7152099013
2024-04-26 20:28:34,839 - aiogram.event - INFO - Update id=537262943 is handled. Duration 1670 ms by bot id=7152099013
2024-04-26 20:28:38,465 - aiogram.event - INFO - Update id=537262944 is handled. Duration 149 ms by bot id=7152099013
2024-04-26 20:28:45,566 - aiogram.event - INFO - Update id=537262945 is handled. Duration 1589 ms by bot id=7152099013
2024-04-26 20:31:12,285 - aiogram.event - INFO - Update id=537262946 is handled. Duration 252 ms by bot id=7152099013
2024-04-26 20:31:18,727 - aiogram.event - INFO - Update id=537262947 is not handled. Duration 1488 ms by bot id=7152099013
2024-04-26 20:31:18,728 - aiogram.event - ERROR - Cause exception while process update id=537262947 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:31:26,323 - aiogram.event - INFO - Update id=537262948 is not handled. Duration 1049 ms by bot id=7152099013
2024-04-26 20:31:26,323 - aiogram.event - ERROR - Cause exception while process update id=537262948 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:31:41,983 - aiogram.event - INFO - Update id=537262949 is handled. Duration 1598 ms by bot id=7152099013
2024-04-26 20:31:47,035 - aiogram.event - INFO - Update id=537262950 is handled. Duration 117 ms by bot id=7152099013
2024-04-26 20:31:53,349 - aiogram.event - INFO - Update id=537262951 is handled. Duration 2006 ms by bot id=7152099013
2024-04-26 20:32:45,376 - aiogram.event - INFO - Update id=537262952 is handled. Duration 260 ms by bot id=7152099013
2024-04-26 20:32:49,352 - aiogram.event - INFO - Update id=537262953 is handled. Duration 1650 ms by bot id=7152099013
2024-04-26 20:33:34,662 - bot.handlers.user_handlers - INFO - User id=1071020716 is_bot=False first_name='Sergei' last_name='Zelenin' username='szely' language_code='ru' is_premium=None added_to_attachment_menu=None can_join_groups=None can_read_all_group_messages=None supports_inline_queries=None started the conversation.
2024-04-26 20:33:34,663 - aiogram.event - INFO - Update id=537262954 is handled. Duration 280 ms by bot id=7152099013
2024-04-26 20:33:37,756 - aiogram.event - INFO - Update id=537262955 is handled. Duration 651 ms by bot id=7152099013
2024-04-26 20:33:39,554 - aiogram.event - INFO - Update id=537262956 is handled. Duration 379 ms by bot id=7152099013
2024-04-26 20:33:41,141 - aiogram.event - INFO - Update id=537262957 is handled. Duration 174 ms by bot id=7152099013
2024-04-26 20:33:47,181 - aiogram.event - INFO - Update id=537262958 is not handled. Duration 1830 ms by bot id=7152099013
2024-04-26 20:33:47,181 - aiogram.event - ERROR - Cause exception while process update id=537262958 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:33:53,068 - aiogram.event - INFO - Update id=537262959 is handled. Duration 127 ms by bot id=7152099013
2024-04-26 20:33:57,725 - aiogram.event - INFO - Update id=537262960 is not handled. Duration 1103 ms by bot id=7152099013
2024-04-26 20:33:57,725 - aiogram.event - ERROR - Cause exception while process update id=537262960 by bot id=7152099013
UnknownValueError: 
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/handlers/user_handlers.py", line 121, in search
    text = speach_rec(file_name_wav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/bot/other_methods/speach_rec.py", line 22, in speach_rec
    text = r.recognize_google(audio, language='ru')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 251, in recognize_legacy
    return output_parser.parse(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 124, in parse
    actual_result = self.convert_to_result(response_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a1234/PycharmProjects/pythonDiploma/venv/lib/python3.11/site-packages/speech_recognition/recognizers/google.py", line 173, in convert_to_result
    raise UnknownValueError()
speech_recognition.exceptions.UnknownValueError
2024-04-26 20:34:05,342 - aiogram.event - INFO - Update id=537262961 is handled. Duration 1972 ms by bot id=7152099013
2024-04-26 20:34:17,819 - aiogram.event - INFO - Update id=537262962 is handled. Duration 136 ms by bot id=7152099013
2024-04-26 20:34:23,715 - aiogram.event - INFO - Update id=537262963 is handled. Duration 2690 ms by bot id=7152099013
2024-04-26 20:41:16,645 - aiogram.dispatcher - WARNING - Received SIGINT signal
2024-04-26 20:41:16,650 - aiogram.dispatcher - INFO - Polling stopped for bot @test2323werwe2_bot id=7152099013 - 'test2'
2024-04-26 20:41:16,652 - aiogram.dispatcher - INFO - Polling stopped
